version: '3'

services:
  product-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    volumes:
      - ./postgres-data/product:/var/lib/postgresql/data

  product:
    build: ./product
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_TYPE: postgres
      DB_HOST: product-db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: product_db

  order-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    volumes:
      - ./postgres-data/order:/var/lib/postgresql/data

  order:
    build: ./order
    restart: always
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      DB_TYPE: postgres
      DB_HOST: order-db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: order_db

  inventory-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    volumes:
      - ./postgres-data/inventory:/var/lib/postgresql/data

  inventory:
    build: ./inventory
    restart: always
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      DB_TYPE: postgres
      DB_HOST: inventory-db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: inventory_db